#Main purpose of this code is to translate the turkish names in the quarterly_visitors_by_country.csv to 3 letter codes

import pandas as pd

# Load the tourist CSV
df_tourists = pd.read_csv("seasonal_visitors_by_country.csv")

# Add year column
df_tourists["Year"] = pd.to_datetime(df_tourists["date"]).dt.year

# Turkish to 3 letter code
turkish_to_iso3 = {
  "ABD":"USA",
  "Irak":"IRQ",
  "Bhutan":"BTN",
  "Çekya":"CZW",
  "Cabo Verde":"CPV",
  "Sao Tome":"STP",
  "Bahama Adaları":"BHS",
  "Kosova":"KOS",
  "Kongo Cumhuriyeti":"COG",
  "Saint Vincent":"VCT",
  "Saint Kitts":"KNA",
  "Mikronezya":"FSM",
  "Surinam":"SUR",
  "Yeşil Burun Adalar":"CPV",
  "Afganistan":"AFG",
  "Arnavutluk":"ALB",
  "Andorra":"AND",
  "Ermenistan":"ARM",
  "Avusturya":"AUT",
  "Azerbaycan":"AZE",
  "Belçika":"BEL",
  "Bulgaristan":"BGR",
  "Bosna-Hersek":"BIH",
  "Belarus":"BLR",
  "İsviçre":"CHE",
  "Kıbrıs":"CYP",
  "Çek Cumhuriyeti":"CZE",
  "Almanya":"DEU",
  "Danimarka":"DNK",
  "İspanya":"ESP",
  "Estonya":"EST",
  "Finlandiya":"FIN",
  "Fransa":"FRA",
  "Faroe Adaları":"FRO",
  "Birleşik Krallık":"GBR",
  "Gürcistan":"GEO",
  "Cebelitarık":"GIB",
  "Yunanistan":"GRC",
  "Grönland":"GRL",
  "Hırvatistan":"HRV",
  "Macaristan":"HUN",
  "Man Adası":"IMN",
  "İrlanda":"IRL",
  "İzlanda":"ISL",
  "İtalya":"ITA",
  "Kazakistan":"KAZ",
  "Kırgızistan":"KGZ",
  "Lihtenştayn":"LIE",
  "Litvanya":"LTU",
  "Lüksemburg":"LUX",
  "Letonya":"LVA",
  "Monako":"MCO",
  "Moldova":"MDA",
  "Kuzey Makedonya":"MKD",
  "Karadağ":"MNE",
  "Hollanda":"NLD",
  "Norveç":"NOR",
  "Polonya":"POL",
  "Portekiz":"PRT",
  "Romanya":"ROU",
  "Rusya":"RUS",
  "San Marino":"SMR",
  "Sırbistan":"SRB",
  "Slovakya":"SVK",
  "Slovenya":"SVN",
  "İsveç":"SWE",
  "Tacikistan":"TJK",
  "Türkmenistan":"TKM",
  "Türkiye":"TUR",
  "Ukrayna":"UKR",
  "Özbekistan":"UZB",
  "Arjantin":"ARG",
  "Antigua ve Barbuda":"ATG",
  "Bahamalar":"BHS",
  "Belize":"BLZ",
  "Bolivya":"BOL",
  "Brezilya":"BRA",
  "Barbados":"BRB",
  "Şili":"CHL",
  "Kolombiya":"COL",
  "Kosta Rika":"CRI",
  "Küba":"CUB",
  "Curaçao":"CUW",
  "Cayman Adaları":"CYM",
  "Dominika":"DMA",
  "Dominik Cumhuriyeti":"DOM",
  "Ekvador":"ECU",
  "Grenada":"GRD",
  "Guatemala":"GTM",
  "Guyana":"GUY",
  "Honduras":"HND",
  "Haiti":"HTI",
  "Jamaika":"JAM",
  "Saint Kitts ve Nevis":"KNA",
  "Saint Lucia":"LCA",
  "Saint Martin":"MAF",
  "Meksika":"MEX",
  "Nikaragua":"NIC",
  "Panama":"PAN",
  "Peru":"PER",
  "Porto Riko":"PRI",
  "Paraguay":"PRY",
  "El Salvador":"SLV",
  "Surinam":"SUR",
  "Sint Maarten":"SXM",
  "Turks ve Caicos Adaları":"TCA",
  "Trinidad ve Tobago":"TTO",
  "Uruguay":"URY",
  "Saint Vincent ve Grenadinler":"VCT",
  "Venezuela":"VEN",
  "Birleşik Krallık Virgin Adaları":"VGB",
  "Amerika Birleşik Devletleri":"USA",
  "Birleşik Arap Emirlikleri":"ARE",
  "Bahreyn":"BHR",
  "Cibuti":"DJI",
  "Cezayir":"DZA",
  "Mısır":"EGY",
  "İran":"IRN",
  "Irak":"IRQ",
  "İsrail":"ISR",
  "Ürdün":"JOR",
  "Kuveyt":"KWT",
  "Lübnan":"LBN",
  "Libya":"LBY",
  "Fas":"MAR",
  "Malta":"MLT",
  "Umman":"OMN",
  "Filistin":"PSE",
  "Katar":"QAT",
  "Suudi Arabistan":"SAU",
  "Suriye":"SYR",
  "Tunus":"TUN",
  "Yemen":"YEM",
  "Bermuda":"BMU",
  "Kanada":"CAN",
  "Bangladeş":"BGD",
  "Butan":"BTN",
  "Hindistan":"IND",
  "Sri Lanka":"LKA",
  "Maldivler":"MDV",
  "Nepal":"NPL",
  "Pakistan":"PAK",
  "Angola":"AGO",
  "Burundi":"BDI",
  "Benin":"BEN",
  "Burkina Faso":"BFA",
  "Botsvana":"BWA",
  "Orta Afrika Cumhuriyeti":"CAF",
  "Fildişi Sahili":"CIV",
  "Kamerun":"CMR",
  "Kongo (Demokratik Cumhuriyet)":"COD",
  "Kongo (Cumhuriyet)":"COG",
  "Komorlar":"COM",
  "Cape Verde":"CPV",
  "Eritre":"ERI",
  "Etiyopya":"ETH",
  "Gabon":"GAB",
  "Gana":"GHA",
  "Gine":"GIN",
  "Gambiya":"GMB",
  "Gine-Bisau":"GNB",
  "Ekvator Ginesi":"GNQ",
  "Kenya":"KEN",
  "Liberya":"LBR",
  "Lesotho":"LSO",
  "Madagaskar":"MDG",
  "Mali":"MLI",
  "Mozambik":"MOZ",
  "Moritanya":"MRT",
  "Aruba":"ABW",
  "Anguilla":"AIA",
  "Åland Adaları":"ALA",
  "Amerikan Samoası":"ASM",
  "Antarktika":"ATA",
  "Fransız Güney Toprakları":"ATF",
  "Avustralya":"AUS",
  "Bonaire, Sint Eustatius ve Saba":"BES",
  "Saint Barthélemy":"BLM",
  "Brunei":"BRN",
  "Bouvet Adası":"BVT",
  "Cocos (Keeling) Adaları":"CCK",
  "Çin":"CHN",
  "Cook Adaları":"COK",
  "Christmas Adası":"CXR",
  "Batı Sahra":"ESH",
  "Fiji":"FJI",
  "Falkland Adaları (Malvinas)":"FLK",
  "Mikronezya (Federal Devletleri)":"FSM",
  "Guernsey":"GGY",
  "Guadeloupe":"GLP",
  "Fransız Guyanası":"GUF",
  "Guam":"GUM",
  "Hong Kong":"HKG",
  "Heard Adası ve McDonald Adaları":"HMD",
  "Endonezya":"IDN",
  "Britanya Hint Okyanusu Toprakları":"IOT",
  "Jersey":"JEY",
  "Japonya":"JPN",
  "Kamboçya":"KHM",
  "Kiribati":"KIR",
  "Güney Kore":"KOR",
  "Laos":"LAO",
  "Makao":"MAC",
  "Marshall Adaları":"MHL",
  "Myanmar":"MMR",
  "Moğolistan":"MNG",
  "Kuzey Mariana Adaları":"MNP",
  "Montserrat":"MSR",
  "Martinik":"MTQ",
  "Mauritius":"MUS",
  "Malavi":"MWI",
  "Malezya":"MYS",
  "Mayotte":"MYT",
  "Namibya":"NAM",
  "Yeni Kaledonya":"NCL",
  "Nijer":"NER",
  "Norfolk Adası":"NFK",
  "Nijerya":"NGA",
  "Niue":"NIU",
  "Nauru":"NRU",
  "Yeni Zelanda":"NZL",
  "Pitcairn Adaları":"PCN",
  "Filipinler":"PHL",
  "Palau":"PLW",
  "Papua Yeni Gine":"PNG",
  "Kuzey Kore":"PRK",
  "Fransız Polinezyası":"PYF",
  "Réunion":"REU",
  "Ruanda":"RWA",
  "Sudan":"SDN",
  "Senegal":"SEN",
  "Singapur":"SGP",
  "Güney Georgia ve Güney Sandwich Adaları":"SGS",
  "Saint Helena, Ascension ve Tristan da Cunha":"SHN",
  "Svalbard ve Jan Mayen":"SJM",
  "Solomon Adaları":"SLB",
  "Sierra Leone":"SLE",
  "Somali":"SOM",
  "Saint Pierre ve Miquelon":"SPM",
  "Güney Sudan":"SSD",
  "São Tomé ve Príncipe":"STP",
  "Esvatini (eski adıyla Svaziland)":"SWZ",
  "Seyşeller":"SYC",
  "Çad":"TCD",
  "Togo":"TGO",
  "Tayland":"THA",
  "Tokelau":"TKL",
  "Timor-Leste":"TLS",
  "Tonga":"TON",
  "Tuvalu":"TUV",
  "Tayvan":"TWN",
  "Tanzanya":"TZA",
  "Uganda":"UGA",
  "ABD Küçük Dış Adaları":"UMI",
  "Vatikan":"VAT",
  "ABD Virgin Adaları":"VIR",
  "Vietnam":"VNM",
  "Vanuatu":"VUT",
  "Wallis ve Futuna":"WLF",
  "Samoa":"WSM",
  "Güney Afrika":"ZAF",
  "Zambiya":"ZMB",
  "Zimbabve":"ZWE",
  "Amerikan Samoası": "ASM",
  
}



# Map Turkish country names to 3 letter codes
df_tourists["Country Code"] = df_tourists["uyruk"].map(turkish_to_iso3)

# Drop rows without a code
df_tourists = df_tourists.dropna(subset=["Country Code"])

# Keep only relevant columns
df_cleaned = df_tourists[["date", "Country Code", "ziyaretci_sayisi"]]

# Save to CSV
df_cleaned.to_csv("seasonal_tourist_data.csv", index=False)

print("File saved as seasonal_tourist_data.csv")
